[#{context}-how-to-reset-a-root-password]
= How to Reset the root Password
 
include::{partialsdir}/unreviewed-message.adoc[]
 
A root password may be set up while installing Fedora Linux, although it is now suggested to leave the root account locked and use `sudo`.
There are two common methods to reset the root password if it is forgotten or lost.
 
* In Rescue Mode
 
* Using a Fedora Live Media (USB/DVD/CD)
 
 
[[sect-how-to-reset-the-password-from-emergency-or-single-user-mode]]
== How to reset the root password in Rescue Mode
 
[NOTE]
 
====
 
Changing passwords as root will not prompt for the old password.
 
====
 
While booting the system the xref:bootloading-with-grub2.adoc[GRUB2] menu will be displayed.
To boot the system into rescue mode using `bash` follow these steps:
 
. Select the boot entry you wish to edit with the arrow keys.
 
. Select the entry you with to edit by pressing *e*.
 
. Use the arrow keys to go to select the line begging with `linux`, `linux16`, or `linuxefi`.
 
. Go the the end of that line and include a space and the following `rw init=/bin/bash`.
 [Note]
 ====
  If your disk is encrypted, you may need to add `plymouth.enable=0`
 ====
. Press *Ctrl-x* or *F10* to boot the entry
 
. Run the command:
+
[source,bash]
 
----
 
passwd
 
----
+
You will be prompted to enter the new root password twice.
 
. Restore the SELinux context and permissions with:
+
[source,bash]
 
----
 
touch /.autorelabel
 
----
 
+
 
[WARNING]
 
====
 
If you do not restore the SELinux permissions, the boot process may fail.
You may have to do a hard-reboot and start back at step 1.
 
====
 
. Reboot the machine with:
+
[source,bash]
 
----
 
/sbin/reboot -f
 
----
 
The system may take a moment to boot while SELinux relabels its permissions on the filesystem.
If you see the Plymouth boot screen you can press the `ESC` key on your keyboard to view the SELinux progress.
Once it is complete, your system is ready and your root password has been successfully changed.
 
[[sect-reset-password-using-the-fedora-live-media]]
== How to reset the root password with a Fedora Live Media
 
[NOTE]
 
====
 
To download and create a live USB of Fedora Workstation, follow the instructions on the xref:creating-and-using-a-live-installation-image.adoc[Fedora USB Live Media Quick Doc].
 
====
 
. Boot the Live installation media and choose `Try Fedora`.
 
. From the desktop, open a terminal and switch to root using `su` (the system will not ask for a password).
 
. To view your hard drive device nodes, enter `df -H` into the terminal.
  For this example we will use `/dev/sda1` for the `/boot` partition and `/dev/sda2` for the root `/` partition.
+
If you are using LVM partitions, type: `sudo lvscan` and note the `/dev` path of your root partition.
For this example we will use `/dev/fedora/root`.
 
. Create a directory for the mount point (use the `-p` option to create subdirectories):
+
[source,bash]
 
----
 
mkdir -p /mnt/sysimage/boot
 
----
 
. Mount the `/` (root) partition (be sure to use the actual device node or LVM path of your root `/` partition):
+
To mount root on a *standard partition* scheme enter:
+
[source,bash]
 
----
 
mount /dev/sda2 /mnt/sysimage
 
----
+
To mount root on an *LVM partition* scheme enter:
+
[source,bash]
 
----
 
mount /dev/fedora/root /mnt/sysimage
 
----
 
. Continue the process by mounting `/boot`, `proc`, `/dev`, and `/run` with:
+
[source,bash]
 
----
 
mount /dev/sda1 /mnt/sysimage/boot
 
mount -t proc none /mnt/sysimage/proc
 
mount -o bind /dev /mnt/sysimage/dev
 
mount -o bind /run /mnt/sysimage/run
 
----
 
. `chroot` to the mounted root partition with:
+
[source,bash]
 
----
 
chroot /mnt/sysimage /bin/bash
 
----
 
. Change the root password:
+
[source,bash]
 
----
 
passwd
 
----
 
. Exit out of chroot with:
+
[source,bash]
 
----
 
exit
 
----
+
and exit out of the terminal.
 
. Reboot your system and boot from the hard drive.
 
Congratulations, your root password has been successfully changed.
 
[[sect-additional-troubleshooting]]
== Additional Troubleshooting
 
. If you cannot enter rescue mode because you forgot the Firmware/BIOS password here are some options:
 
.. Refer to your computer's documentation for instructions on resetting the Firmware/BIOS password in CMOS memory.
 
.. Temporarily move the system hard disk to another machine, and follow the procedures above to reset the root password.
 
. If you have set a password for your boot loader, refer to xref:creating-and-using-a-live-installation-image.adoc[Creating and Using a Live Installation Image].
 
. If you want to reset the boot loader password, refer to the instructions on how to link:++https://fedoraproject.org/wiki/Reset_Bootloader_Password++[Reset the Bootloader Password].

// Module included in the following assemblies:
//
// changing-selinux-states-and-modes.adoc

[#{context}-disabling-selinux]
= Disabling SELinux

Use the following procedure to permanently disable SELinux.
 
[IMPORTANT]
====
When SELinux is disabled, SELinux policy is not loaded at all; it is not enforced and AVC messages are not logged. Therefore, all benefits of running SELinux listed in xref:{context}-benefits-of-selinux[Benefits of SELinux] are lost.

It is recommended to use permissive mode instead of permanently disabling SELinux. See xref:{context}-changing-to-permissive-mode[] for more information about permissive mode.
====

[Warning]
====
Disabling SELinux using the SELINUX=disabled option in the /etc/selinux/config results in a process in which the kernel boots with SELinux enabled and switches to disabled mode later in the boot process. Because memory leaks and race conditions causing kernel panics can occur, prefer disabling SELinux by adding the selinux=0 parameter to the kernel command line as described in Changing SELinux modes at boot time if your scenario really requires to completely disable SELinux.
====

.Prerequisites

* The [package]`grubby` package is installed:
+
[subs="quotes"]
----
$ *rpm -q grubby*
grubby-_version_
----

.Procedure

. Open the `/etc/selinux/config` file in a text editor of your choice, for example:
+
[subs="quotes"]
----
# vi /etc/selinux/config
----

. Configure the SELINUX=disabled option:
+
[subs="quotes"]
----
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of these two values:
#       targeted - Targeted processes are protected,
#       mls - Multi Level Security protection.
SELINUXTYPE=targeted
----

. Save the change, and restart your system:
+
----
# reboot
----

.Verification 

* After reboot, confirm that the [command]`getenforce` command returns `Disabled`:
+
[subs="quotes"]
----
$ *getenforce*
Disabled
----
// Module included in the following assemblies:
//
// assembly_changing-selinux-states-and-modes.adoc

[#{context}-Enabling_and_Disabling_SELinux-Dracut-parameters]
= Changing SELinux Modes at Boot Time

On boot, you can set several kernel parameters to change the way SELinux runs:

enforcing=0::  Setting this parameter causes the system to start in permissive mode, which is useful when troubleshooting issues. Using permissive mode might be the only option to detect a problem if your file system is too corrupted. Moreover, in permissive mode, the system continues to create the labels correctly. The AVC messages that are created in this mode can be different than in enforcing mode.
+
In permissive mode, only the first denial from a series of the same denials is reported. However, in enforcing mode, you might get a denial related to reading a directory, and an application stops. In permissive mode, you get the same AVC message, but the application continues reading files in the directory and you get an AVC for each denial in addition.

selinux=0::  This parameter causes the kernel to not load any part of the SELinux infrastructure. The init scripts notice that the system booted with the [option]`selinux=0` parameter and touch the `/.autorelabel` file. This causes the system to automatically relabel the next time you boot with SELinux enabled.
+
[IMPORTANT]
====
Using the [option]`selinux=0` parameter is not recommended. To debug your system, prefer using permissive mode.
====

autorelabel=1::  This parameter forces the system to relabel similarly to the following commands:
+
----
# touch /.autorelabel
# reboot
----
+
If a file system contains a large amount of mislabeled objects, start the system in permissive mode to make the autorelabel process successful.

For additional SELinux-related kernel boot parameters, such as [option]`checkreqprot`, see the `kernel-parameters.txt` file. This file is available in the source package of your Linux kernel (.src.rpm). To download the source package containing the currently used kernel:
----
~]# dnf download --source kernel
----
