[#{context}-how-to-reset-a-root-password]
= How to Reset the root Password
 
include::{partialsdir}/unreviewed-message.adoc[]
 
A root password may be set up while installing Fedora Linux, although it is now suggested to leave the root account locked and use `sudo`.
There are two common methods to reset the root password if it is forgotten or lost.
 
* In Rescue Mode
 
* Using a Fedora Live Media (USB/DVD/CD)
 
 
[[sect-how-to-reset-the-password-from-emergency-or-single-user-mode]]
== How to reset the root password in Rescue Mode
 
[NOTE]
 
====
 
Changing passwords as root will not prompt for the old password.
 
====
 
While booting the system the xref:bootloading-with-grub2.adoc[GRUB2] menu will be displayed.
To boot the system into rescue mode using `bash` follow these steps:
 
. Select the boot entry you wish to edit with the arrow keys.
 
. Select the entry you with to edit by pressing *e*.
 
. Use the arrow keys to go to select the line begging with `linux`, `linux16`, or `linuxefi`.
 
. Go the the end of that line and include a space and the following `rw init=/bin/bash`.
 [Note]
 ====
  If your disk is encrypted, you may need to add `plymouth.enable=0`
 ====
. Press *Ctrl-x* or *F10* to boot the entry
 
. Run the command:
+
[source,bash]
 
----
 
passwd
 
----
+
You will be prompted to enter the new root password twice.
 
. Restore the SELinux context and permissions with:
+
[source,bash]
 
----
 
touch /.autorelabel
 
----
 
+
 
[WARNING]
 
====
 
If you do not restore the SELinux permissions, the boot process may fail.
You may have to do a hard-reboot and start back at step 1.
 
====
 
. Reboot the machine with:
+
[source,bash]
 
----
 
/sbin/reboot -f
 
----
 
The system may take a moment to boot while SELinux relabels its permissions on the filesystem.
If you see the Plymouth boot screen you can press the `ESC` key on your keyboard to view the SELinux progress.
Once it is complete, your system is ready and your root password has been successfully changed.
 
[[sect-reset-password-using-the-fedora-live-media]]
== How to reset the root password with a Fedora Live Media
 
[NOTE]
 
====
 
To download and create a live USB of Fedora Workstation, follow the instructions on the xref:creating-and-using-a-live-installation-image.adoc[Fedora USB Live Media Quick Doc].
 
====
 
. Boot the Live installation media and choose `Try Fedora`.
 
. From the desktop, open a terminal and switch to root using `su` (the system will not ask for a password).
 
. To view your hard drive device nodes, enter `df -H` into the terminal.
  For this example we will use `/dev/sda1` for the `/boot` partition and `/dev/sda2` for the root `/` partition.
+
If you are using LVM partitions, type: `sudo lvscan` and note the `/dev` path of your root partition.
For this example we will use `/dev/fedora/root`.
 
. Create a directory for the mount point (use the `-p` option to create subdirectories):
+
[source,bash]
 
----
 
mkdir -p /mnt/sysimage/boot
 
----
 
. Mount the `/` (root) partition (be sure to use the actual device node or LVM path of your root `/` partition):
+
To mount root on a *standard partition* scheme enter:
+
[source,bash]
 
----
 
mount /dev/sda2 /mnt/sysimage
 
----
+
To mount root on an *LVM partition* scheme enter:
+
[source,bash]
 
----
 
mount /dev/fedora/root /mnt/sysimage
 
----
 
. Continue the process by mounting `/boot`, `proc`, `/dev`, and `/run` with:
+
[source,bash]
 
----
 
mount /dev/sda1 /mnt/sysimage/boot
 
mount -t proc none /mnt/sysimage/proc
 
mount -o bind /dev /mnt/sysimage/dev
 
mount -o bind /run /mnt/sysimage/run
 
----
 
. `chroot` to the mounted root partition with:
+
[source,bash]
 
----
 
chroot /mnt/sysimage /bin/bash
 
----
 
. Change the root password:
+
[source,bash]
 
----
 
passwd
 
----
 
. Exit out of chroot with:
+
[source,bash]
 
----
 
exit
 
----
+
and exit out of the terminal.
 
. Reboot your system and boot from the hard drive.
 
Congratulations, your root password has been successfully changed.
 
[[sect-additional-troubleshooting]]
== Additional troubleshooting
 
. If you cannot enter rescue mode because you forgot the Firmware/BIOS password here are some options:
 
.. Refer to your computer's documentation for instructions on resetting the Firmware/BIOS password in CMOS memory.
 
.. Temporarily move the system hard disk to another machine, and follow the procedures above to reset the root password.
 
. If you have set a password for your boot loader, refer to xref:creating-and-using-a-live-installation-image.adoc[Creating and Using a Live Installation Image].
 
. If you want to reset the boot loader password, refer to the instructions on how to link:++https://fedoraproject.org/wiki/Reset_Bootloader_Password++[Reset the Bootloader Password].

// Module included in the following assemblies:
//
// changing-selinux-states-and-modes.adoc