= Troubleshooting problems related to SELinux
:toc:

If you plan to enable SELinux on systems where it has been previously disabled or if you run a service in a non-standard configuration, you might need to troubleshoot situations potentially blocked by SELinux. Note that in most cases, SELinux denials are signs of misconfiguration.

== Identifying SELinux denials

Follow only the necessary steps from this procedure; in most cases, you need to perform just step 1.

*Procedure*

. When your scenario is blocked by SELinux, the [command]`/var/log/audit/audit.log` file is the first place to check for more information about a denial. To query Audit logs, use the `ausearch` tool. Because the SELinux decisions, such as allowing or disallowing access, are cached and this cache is known as the Access Vector Cache (AVC), use the `AVC` and `USER_AVC` values for the message type parameter, for example:
+
----
# ausearch -m AVC,USER_AVC,SELINUX_ERR,USER_SELINUX_ERR -ts recent
----
+
If there are no matches, check if the Audit daemon is running. If it does not, repeat the denied scenario after you start auditd and check the Audit log again.

. In case auditd is running, but there are no matches in the output of ausearch, check messages provided by the systemd Journal:
+
----
# journalctl -t setroubleshoot
----

. If SELinux is active and the Audit daemon is not running on your system, then search for certain SELinux messages in the output of the dmesg command:
+
----
# dmesg | grep -i -e type=1300 -e type=1400
----

. Even after the previous three checks, it is still possible that you have not found anything. In this case, AVC denials can be silenced because of `dontaudit` rules.
+
To temporarily disable `dontaudit` rules, allowing all denials to be logged:
+
----
# semodule -DB
----
+
After re-running your denied scenario and finding denial messages using the previous steps, the following command enables `dontaudit` rules in the policy again:
+
----
# semodule -B
----

. If you apply all four previous steps, and the problem still remains unidentified, consider if SELinux really blocks your scenario:
* Switch to permissive mode:
+ 
----
# setenforce 0
$ getenforce
Permissive
----
* Repeat your scenario.

If the problem still occurs, something different than SELinux is blocking your scenario.

== Analyzing SELinux denial messages

After identifying that SELinux is blocking your scenario, you might need to analyze the root cause before you choose a fix.

*Prerequisites*

** The `policycoreutils-python-utils` and `setroubleshoot-server` packages are installed on your system.

*Procedure*

. List more details about a logged denial using the `sealert` command, for example:
+
----
$ sealert -l "*"
SELinux is preventing /usr/bin/passwd from write access on the file
/root/test.

*****  Plugin leaks (86.2 confidence) suggests *****************************

If you want to ignore passwd trying to write access the test file,
because you believe it should not need this access.
Then you should report this as a bug.
You can generate a local policy module to dontaudit this access.
Do
# ausearch -x /usr/bin/passwd --raw | audit2allow -D -M my-passwd
# semodule -X 300 -i my-passwd.pp

*****  Plugin catchall (14.7 confidence) suggests **************************

...

Raw Audit Messages
type=AVC msg=audit(1553609555.619:127): avc:  denied  { write } for
pid=4097 comm="passwd" path="/root/test" dev="dm-0" ino=17142697
scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023
tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=0

..

Hash: passwd,passwd_t,admin_home_t,file,write
----

. If the output obtained in the previous step does not contain clear suggestions:

* Enable full-path auditing to see full paths to accessed objects and to make additional Linux Audit event fields visible:
+
----
# auditctl -w /etc/shadow -p w -k shadow-write
----

* Clear the `setroubleshoot` cache:
+
----
# rm -f /var/lib/setroubleshoot/setroubleshoot.xml
----

* Reproduce the problem.
* Repeat step 1.
+
After you finish the process, disable full-path auditing:
+
----
# auditctl -W /etc/shadow -p w -k shadow-write
----

. If `sealert` returns only `catchall` suggestions or suggests adding a new rule using the `audit2allow` tool, match your problem with examples listed and explained in SELinux denials in the Audit log.

*Additional resources*

* `sealert(8)` man page


